language: go
go:
  - 1.12.x
install:
  - mkdir -p $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git
  - mv $TRAVIS_BUILD_DIR $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/hugo
  - cd hugo
  - go install
script:
  - hugo
  - python --version
  - sudo pip install awscli
  - export AWS_DEFAULT_REGION="eu-west-1"
  - export AWS_ACCESS_KEY_ID=$AK
  - export AWS_SECRET_ACCESS_KEY=$SK
  - aws s3 sync public/ s3://www.4-2.xyz/ --delete

notifications:
    email:
        on_failure: always
    slack: wbearcorp:lxW2iytWMmecA5W3leRB9Wnf
