language: go
install: go get -v github.com/spf13/hugo
script:
  - hugo
  - python --version
  - sudo pip install s3cmd
  - s3cmd sync -v --delete-removed -M -r --access_key=$AK --secret_key=$SK public/ s3://www.4-2.xyz/
notifications:
    email:
        on_failure: always