language: go
install: go get -v github.com/spf13/hugo
script:
  - hugo
deploy:
  provider: s3
  access_key_id: $AK
  secret_access_key: $SK
  bucket: "www.4-2.xyz"
  skip_cleanup: true
  local_dir: public
  region: "eu-west-1"
notifications:
    email:
        on_failure: always
    slack: wbearcorp:lxW2iytWMmecA5W3leRB9Wnf