baseurl = "https://www.4-2.xyz"
title = "4-2"
theme = "erblog"
languageCode = "en-us"
paginate = 15

[params]
  Keywords = "wbearcorp, jeremy bunlon"
  Description = "un site, et c'est deja bien"
  showHeader = true
  showTags = true
  debug = false

  