baseurl = "https://www.4-2.xyz"
title = "4-2"
theme = "mondrian"
languageCode = "en-us"
paginate = 15

[menu]
  [[menu.main]]
    name = "posts"
    url = "/post"
    weight = 1
  [[menu.main]]
    name = "sketches"
    url = "/sketch"
    weight = 2

[params]
  Keywords = "wbearcorp, jeremy bunlon"
  Description = "un site, et c'est deja bien"
  showHeader = true
  showTags = true
  debug = false
  [params.colors]
    post = "orangered"
    posts = "gold"
    page = "blue"
    sketch = "limegreen"

  